debug: true
server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    data-format: yyyy-MM-dd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: GMT+8
    data-format: yyyy-MM-dd HH:mm:ss SSS
  datasource:
    url: jdbc:mysql://localhost:3306/my_account_book?useSSL=false&serverTimezone=GMT
    username: my_account_book
    password: my_account_book
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
#    com:
#      nxy006:
#        project:
#          myaccountbook:
#            bean:
#              repository: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE